sonar.projectKey=run_4_tree
sonar.projectName=run_4_tree
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test

# Comma-separated paths to directories with source files (required)
sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
